// Generated by https://quicktype.io

export interface BitacoraInterface {
    id: number;
    id_usuario: number;
    hora_ini: string;
    hora_fin: string;
    createdAt: string;
    updatedAt: string;
    estado: boolean;
    correo: string;
    password: string;
    nombre: string;
    img: null;
    google: boolean;
    id_rol: number;
    celular: number;
    accion: string;
    id_bitacora: number;
}
